-- =============================================================================
-- Universal IDE Event Collection Platform - initial schema
--
-- Design notes:
--   * raw_events is RANGE-partitioned by month on `timestamp`. At the target
--     scale (millions -> billions of rows) this keeps index size bounded,
--     makes retention a DETACH+DROP instead of a mass DELETE, and lets the
--     planner prune whole months for time-bounded analytics queries.
--   * Idempotency is enforced by a UNIQUE constraint on (event_id, timestamp).
--     The partition key must participate in the unique index on a partitioned
--     table, hence the composite. The consumer upserts on this constraint, so
--     redelivery from Kafka is a no-op rather than a duplicate row.
--   * Payloads are JSONB so new event types need no migration.
-- =============================================================================

CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- -----------------------------------------------------------------------------
-- users
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS users (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    external_id     TEXT UNIQUE,
    email           TEXT UNIQUE,
    display_name    TEXT,
    -- Global telemetry opt-out. Honored by the consumer as a hard gate: when
    -- false, incoming events for this user are discarded, not persisted.
    telemetry_enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- -----------------------------------------------------------------------------
-- installations: one row per (user, IDE, machine) extension install
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS installations (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id         UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    ide_name        TEXT NOT NULL,
    ide_version     TEXT,
    extension_version TEXT,
    machine_id      TEXT,
    platform        TEXT,
    -- Argon2/bcrypt-style hash of the installation token. The plaintext token
    -- is returned to the extension once at registration and never stored.
    token_hash      TEXT NOT NULL,
    token_issued_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    revoked_at      TIMESTAMPTZ,
    last_seen_at    TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_installations_user_id ON installations(user_id);
CREATE INDEX IF NOT EXISTS idx_installations_ide_name ON installations(ide_name);
CREATE UNIQUE INDEX IF NOT EXISTS idx_installations_token_hash ON installations(token_hash);

-- -----------------------------------------------------------------------------
-- enrollment_codes: short-lived codes exchanged for installation credentials
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS enrollment_codes (
    code_hash       TEXT PRIMARY KEY,
    user_id         UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    expires_at      TIMESTAMPTZ NOT NULL,
    consumed_at     TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_enrollment_codes_user_id ON enrollment_codes(user_id);
CREATE INDEX IF NOT EXISTS idx_enrollment_codes_expires_at ON enrollment_codes(expires_at);

-- -----------------------------------------------------------------------------
-- projects / repositories / ide_sessions: dimensions referenced by events
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS projects (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id         UUID REFERENCES users(id) ON DELETE CASCADE,
    -- Stable identifier produced by the extension (hash of workspace root).
    external_id     TEXT NOT NULL,
    name            TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (user_id, external_id)
);

CREATE TABLE IF NOT EXISTS repositories (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id         UUID REFERENCES users(id) ON DELETE CASCADE,
    external_id     TEXT NOT NULL,
    name            TEXT,
    default_branch  TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (user_id, external_id)
);

CREATE TABLE IF NOT EXISTS ide_sessions (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    -- session_id as generated by the extension (opaque string).
    external_id     TEXT NOT NULL UNIQUE,
    user_id         UUID REFERENCES users(id) ON DELETE CASCADE,
    installation_id UUID REFERENCES installations(id) ON DELETE CASCADE,
    ide_name        TEXT,
    ide_version     TEXT,
    started_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    ended_at        TIMESTAMPTZ,
    event_count     BIGINT NOT NULL DEFAULT 0,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_ide_sessions_user_id ON ide_sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_ide_sessions_installation_id ON ide_sessions(installation_id);
CREATE INDEX IF NOT EXISTS idx_ide_sessions_started_at ON ide_sessions(started_at DESC);

-- -----------------------------------------------------------------------------
-- raw_events: the primary fact table, partitioned by month
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS raw_events (
    id              UUID NOT NULL DEFAULT gen_random_uuid(),
    event_id        UUID NOT NULL,
    user_id         TEXT NOT NULL,
    installation_id TEXT NOT NULL,
    session_id      TEXT NOT NULL,
    event_type      TEXT NOT NULL,
    ide_name        TEXT NOT NULL,
    ide_version     TEXT,
    "timestamp"     TIMESTAMPTZ NOT NULL,
    workspace_id    TEXT,
    workspace_name  TEXT,
    project_id      TEXT,
    project_name    TEXT,
    repository_id   TEXT,
    repository_name TEXT,
    branch          TEXT,
    file_path       TEXT,
    language        TEXT,
    payload         JSONB NOT NULL DEFAULT '{}'::jsonb,
    metadata        JSONB,
    schema_version  TEXT NOT NULL,
    ingested_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (id, "timestamp"),
    -- Deduplication key: the consumer's ON CONFLICT target.
    CONSTRAINT raw_events_event_id_timestamp_key UNIQUE (event_id, "timestamp")
) PARTITION BY RANGE ("timestamp");

CREATE INDEX IF NOT EXISTS idx_raw_events_user_id ON raw_events(user_id);
CREATE INDEX IF NOT EXISTS idx_raw_events_installation_id ON raw_events(installation_id);
CREATE INDEX IF NOT EXISTS idx_raw_events_session_id ON raw_events(session_id);
CREATE INDEX IF NOT EXISTS idx_raw_events_event_type ON raw_events(event_type);
CREATE INDEX IF NOT EXISTS idx_raw_events_timestamp ON raw_events("timestamp" DESC);
CREATE INDEX IF NOT EXISTS idx_raw_events_project_id ON raw_events(project_id);
CREATE INDEX IF NOT EXISTS idx_raw_events_repository_id ON raw_events(repository_id);
-- Common analytics access path: "this user's events of this type over time".
CREATE INDEX IF NOT EXISTS idx_raw_events_user_type_time
    ON raw_events(user_id, event_type, "timestamp" DESC);
-- GIN index for ad-hoc payload queries.
CREATE INDEX IF NOT EXISTS idx_raw_events_payload ON raw_events USING GIN (payload jsonb_path_ops);

-- Default partition catches anything outside explicitly created ranges so an
-- unexpected clock skew can never fail an insert.
CREATE TABLE IF NOT EXISTS raw_events_default PARTITION OF raw_events DEFAULT;

-- -----------------------------------------------------------------------------
-- event_errors: dead-letter records for events that could not be processed
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS event_errors (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    event_id        UUID,
    installation_id TEXT,
    user_id         TEXT,
    event_type      TEXT,
    error_stage     TEXT NOT NULL,   -- validation | enrichment | persistence
    error_message   TEXT NOT NULL,
    error_details   JSONB,
    raw_payload     JSONB,
    kafka_topic     TEXT,
    kafka_partition INT,
    kafka_offset    BIGINT,
    retry_count     INT NOT NULL DEFAULT 0,
    resolved_at     TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_event_errors_created_at ON event_errors(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_event_errors_stage ON event_errors(error_stage);
CREATE INDEX IF NOT EXISTS idx_event_errors_event_id ON event_errors(event_id);

-- -----------------------------------------------------------------------------
-- Partition management
-- -----------------------------------------------------------------------------
-- Creates the monthly partition covering `target` if it does not yet exist.
-- Call from a scheduled job (pg_cron) a month ahead; the consumer also calls
-- it lazily so a fresh deployment never lands in the default partition.
CREATE OR REPLACE FUNCTION ensure_raw_events_partition(target DATE)
RETURNS VOID AS $$
DECLARE
    start_date DATE := date_trunc('month', target)::DATE;
    end_date   DATE := (date_trunc('month', target) + INTERVAL '1 month')::DATE;
    part_name  TEXT := 'raw_events_' || to_char(start_date, 'YYYY_MM');
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_class WHERE relname = part_name) THEN
        EXECUTE format(
            'CREATE TABLE %I PARTITION OF raw_events FOR VALUES FROM (%L) TO (%L)',
            part_name, start_date, end_date
        );
    END IF;
END;
$$ LANGUAGE plpgsql;

-- Seed the current month plus the next two.
SELECT ensure_raw_events_partition(CURRENT_DATE);
SELECT ensure_raw_events_partition((CURRENT_DATE + INTERVAL '1 month')::DATE);
SELECT ensure_raw_events_partition((CURRENT_DATE + INTERVAL '2 months')::DATE);
