import { spawn } from "child_process";
import { randomBytes } from "crypto";
import { existsSync, writeFileSync } from "fs";
import { resolve } from "path";
import { loadDotEnv } from "./env";

/**
 * `npm run quickstart` - the whole backend in one command.
 *
 * Brings up Kafka and the three services, applies the schema, and waits until
 * the pipeline actually reports ready, then prints the single CLI command a
 * developer runs to start collecting.
 *
 * With no .env it generates one and uses the bundled PostgreSQL, so a fresh
 * clone works without a Supabase account. With a real DATABASE_URL already in
 * .env it uses that and leaves the local database out of it.
 */

const LOCAL_DB_URL = "postgresql://postgres:postgres@localhost:5432/ide_events";
const READY_TIMEOUT_MS = 180_000;

const HEALTH_CHECKS = [
  { label: "Control-plane API", url: "http://localhost:8081/health" },
  { label: "Ingestion API", url: "http://localhost:8080/health" },
  // The consumer's /ready is the one that matters: it stays 503 until both
  // Kafka and the database are connected, which is the actual definition of
  // "the pipeline works".
  { label: "Consumer", url: "http://localhost:8082/ready" },
];

function log(message = ""): void {
  console.log(message);
}

function run(command: string, args: string[], env?: NodeJS.ProcessEnv): Promise<number> {
  return new Promise((resolvePromise, reject) => {
    const child = spawn(command, args, {
      stdio: "inherit",
      env: { ...process.env, ...env },
    });
    child.on("error", reject);
    child.on("close", (code) => resolvePromise(code ?? 1));
  });
}

function runQuiet(
  command: string,
  args: string[],
  env?: NodeJS.ProcessEnv
): Promise<{ code: number; output: string }> {
  return new Promise((resolvePromise) => {
    const child = spawn(command, args, {
      stdio: ["ignore", "pipe", "pipe"],
      env: { ...process.env, ...env },
    });
    let output = "";
    child.stdout?.on("data", (chunk) => (output += chunk));
    child.stderr?.on("data", (chunk) => (output += chunk));
    child.on("error", () => resolvePromise({ code: 1, output }));
    child.on("close", (code) => resolvePromise({ code: code ?? 1, output }));
  });
}

const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

/**
 * A DATABASE_URL still carrying the placeholders from .env.example is worse
 * than none at all: the services would start and fail to connect with a DNS
 * error about a host called "<project-ref>". Treat it as unset.
 */
function isUsableDatabaseUrl(url: string | undefined): url is string {
  return Boolean(url && !url.includes("<") && !url.includes("your-"));
}

function ensureEnvFile(): { created: boolean; path: string } {
  const path = resolve(process.cwd(), ".env");
  if (existsSync(path)) return { created: false, path };

  // Real random secrets rather than the dev-only defaults, so a quickstart
  // that later gets exposed to a network is not signing tokens with a value
  // published in this repository.
  const contents = `# Generated by \`npm run quickstart\`. See .env.example for every option.
#
# No DATABASE_URL is set, so the bundled PostgreSQL is used. To store events in
# Supabase instead, set DATABASE_URL to your Session pooler string and re-run.

NODE_ENV=development
LOG_LEVEL=info

JWT_SECRET=${randomBytes(48).toString("base64")}
ADMIN_API_KEY=${randomBytes(32).toString("hex")}
ALLOW_OPEN_ENROLLMENT=true

KAFKA_BROKERS=kafka:29092
DATABASE_POOL_SIZE=10
`;

  writeFileSync(path, contents, { mode: 0o600 });
  return { created: true, path };
}

async function waitForReady(): Promise<boolean> {
  const deadline = Date.now() + READY_TIMEOUT_MS;
  const pending = new Set(HEALTH_CHECKS.map((c) => c.label));

  while (Date.now() < deadline) {
    for (const check of HEALTH_CHECKS) {
      if (!pending.has(check.label)) continue;
      try {
        const response = await fetch(check.url, {
          signal: AbortSignal.timeout(3000),
        });
        if (response.ok) {
          pending.delete(check.label);
          log(`  ✓ ${check.label}`);
        }
      } catch {
        // Not up yet.
      }
    }
    if (pending.size === 0) return true;
    await sleep(3000);
  }

  log("");
  for (const label of pending) log(`  ✗ ${label} did not become ready`);
  return false;
}

async function migrate(databaseUrl: string): Promise<boolean> {
  // The database accepts connections a moment after the container reports
  // healthy, so a first failure here is expected rather than fatal.
  for (let attempt = 1; attempt <= 10; attempt++) {
    // Passed explicitly: with the bundled database there is no DATABASE_URL in
    // .env for the migration runner to pick up.
    const result = await runQuiet("npx", ["tsx", "scripts/migrate.ts"], {
      DATABASE_URL: databaseUrl,
    });
    if (result.code === 0) {
      log(result.output.trim());
      return true;
    }
    if (attempt === 10) {
      log(result.output.trim());
      return false;
    }
    await sleep(3000);
  }
  return false;
}

async function main(): Promise<number> {
  loadDotEnv();

  log("Universal IDE Event Collection Platform - quickstart\n");

  const docker = await runQuiet("docker", ["compose", "version"]);
  if (docker.code !== 0) {
    log("✗ Docker Compose v2 is not available.");
    log("  Install Docker Desktop, or Docker Engine with the compose plugin,");
    log("  then re-run `npm run quickstart`.");
    return 1;
  }

  const env = ensureEnvFile();
  if (env.created) {
    log(`✓ Generated ${env.path} with fresh secrets`);
  }

  // Docker Compose reads .env itself, so a placeholder there reaches the
  // services no matter what this script decides. Better to stop than to start
  // a stack that will fail resolving a host called "<project-ref>".
  if (process.env.DATABASE_URL && !isUsableDatabaseUrl(process.env.DATABASE_URL)) {
    log("✗ DATABASE_URL in .env still has the placeholders from .env.example.");
    log("  Either fill in your Supabase Session pooler string, or comment the");
    log("  line out to use the bundled PostgreSQL, then re-run.");
    return 1;
  }

  const supabase = isUsableDatabaseUrl(process.env.DATABASE_URL);
  const composeArgs = supabase
    ? ["compose", "up", "-d", "--build"]
    : ["compose", "--profile", "local-db", "up", "-d", "--build"];

  log(
    supabase
      ? "✓ Using the DATABASE_URL from .env"
      : "✓ Using the bundled PostgreSQL (set DATABASE_URL in .env for Supabase)"
  );

  log("\nBuilding workspace packages");
  if ((await run("npm", ["run", "build"])) !== 0) {
    log("\n✗ Build failed. Fix the errors above and re-run.");
    return 1;
  }

  log("\nStarting Kafka and the services (first run pulls images; give it a few minutes)");
  if ((await run("docker", composeArgs)) !== 0) {
    log("\n✗ `docker compose up` failed. See the output above.");
    return 1;
  }

  log("\nApplying the database schema");
  const migrationUrl = supabase ? (process.env.DATABASE_URL as string) : LOCAL_DB_URL;
  if (!(await migrate(migrationUrl))) {
    log("\n✗ Migrations did not apply. Diagnose with:");
    log("    npm run check:db");
    return 1;
  }

  log("\nWaiting for the pipeline to report ready");
  if (!(await waitForReady())) {
    log("\n  Look at what the failing service is saying:");
    log("    docker compose logs consumer --tail 50");
    log("    npm run check:db");
    return 1;
  }

  const adminKey = process.env.ADMIN_API_KEY ?? "dev-admin-key";

  log("\nThe platform is running.");
  log("");
  log("  Ingestion API       http://localhost:8080");
  log("  Control-plane API   http://localhost:8081");
  log("  Consumer metrics    http://localhost:8082/metrics");
  log("  Kafka UI            http://localhost:8090");
  log("");
  log("Install the extension and start collecting - one command:");
  log("");
  // The workspace bin, linked by `npm install`: this is a checkout, so the
  // published package name would send people to npm for code they already have.
  log("    npx ide-collector setup");
  log("");
  log("Open enrollment is on for local development, so no enrollment code is");
  log("needed. To issue one anyway:");
  log("");
  log(`    curl -X POST localhost:8081/v1/enrollment-codes \\`);
  log(`      -H "Authorization: Bearer ${adminKey}" \\`);
  log(`      -H "Content-Type: application/json" \\`);
  log(`      -d '{"email":"you@example.com"}'`);
  log("");
  log("Stop everything with: docker compose down");

  return 0;
}

main()
  .then((code) => process.exit(code))
  .catch((err) => {
    console.error(err instanceof Error ? (err.stack ?? err.message) : String(err));
    process.exit(1);
  });
